CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1000),
    price       DECIMAL                                 NOT NULL,
    PRIMARY KEY (id)
);
